### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by adriaanbd**

### CODE REVIEW

**Comment by dipto0321** [comment]
# Good Job 👏 🚀 

Hi @adriaanbd and @mcrd25,

This project was good. Again the project UI is not that much user-friendly yet. So I will recommend you to work on that. In an example How can I attend an event from UI?. Now let's talk about the projects 🙂 . Here is the checklist

## General

- [x] The project has a descriptive README.md

## Features

### Authentication

- [x] The application has a functional `login` page (It doesn't require authentication according to the Odin Project's description)
- [x] The application uses either a cookie or a session to log in the user.

### Navigation

- [x] The application includes navigation links on top

### Users

#### Model

- [ ] It has a method `previous_events` to retrieve past events.
- [ ] It has a method `upcoming_events` to retrieve upcoming events
- [ ] The class methods use scopes

#### Actions

##### `new`

- [x] It has a view with a form that creates a new User instance when submitted

##### `show`

- [x] Lists all the events the user has created
- [x] Lists all the events where the `user` is an attendee
- [ ] The events are separated in past events and upcoming events.
- [ ] `user_controller` uses separate methods to retrieve the past and upcoming events. E.g.

```ruby
# user_controller.rb
def show
# ...
  @upcoming_events = current_user.upcoming_events
  @prev_events = current_user.previous_events
#..
end
```

### Events

#### Model

- [x] It has a class method to retrieve all past events (`Event.past`)
- [x] It has a class method to retrieve all upcoming events (`Event.upcoming`)
- [x] The class methods use scopes

#### Actions

##### `new`

- [x] It has a view with a form that creates a new Event instance when submitted. The creator of the event is `current_user`
- [x] On `events_controller.rb` in the `new` action, an event is created by using the association between `User` and `Event` and the `build` method. Similar to this:

```ruby
def create
# ...
  @new_event = current_user.events.build
# ...
end
```

##### `index`

- [x] Lists all events separated into Past and Upcoming categories.

##### `show`

- [x] It displays the creator of the event
- [x] It displays the list of attendees
 
Also, please check out these [issues](https://github.com/adriaanbd/rorbrite/issues). After fixing all those things send another request to re-review this project.

Thanks 🙏

**Comment by dipto0321** [comment]
Hi @adriaanbd  and @mcrd25 ,

Please check out these issues and after fixing please send another request to re-review this project.

Thanks 🙏

**Comment by dipto0321** [comment]
# So far so good :clap: 👍 💯 

Hi @adriaanbd and @mcrd25 ,

Good job. Now it's looking good. I am closing #7 and this is from me 👍 . You can merge it into the master. Best of luck for the upcoming project. Thanks for being cooperative and keeping your patience 😌

**Comment by mcrd25** [comment]
Hi @dipto0321 ,

Thanks a lot for reviewing our code! 
Thank you for reviewing our code 😄 and having patience with us.

-
@mcrd25 and @adriaanbd

**Pull request merged**
